apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: nodejs-standard

on:
  workflow_call:
    inputs:
      application-name:
        type: string
        required: true
      version:
        type: string
        required: true
      target-environment:
        type: string
        required: true

jobs:
  build-test-security:

    steps:

      - name: Checkout source code
        uses: cloudbees-io/checkout@v1

      - name: Standard Build Process
        uses: docker://node:20-alpine
        shell: sh
        run: |
          npm install

      - name: Enforce Corporate Security Policy
        uses: docker://node:20-alpine
        shell: sh
        run: |
          npm audit --audit-level=high

      - name: Corporate Quality Gate
        uses: docker://node:20-alpine
        shell: sh
        run: |
          npm test

      - name: Create deployable artifact
        uses: docker://node:20-alpine
        shell: sh
        run: |
          mkdir -p dist
          tar -czf dist/application.tar.gz .

      - name: Register Artifact for Traceability
        id: register-artifact
        uses: cloudbees-io/register-build-artifact@v2
        with:
          name: ${{ inputs.application-name}}
          version: ${{ inputs.version}}
          url: docker.io/alvarotoscano/${{ inputs.application-name }}:${{ inputs.version }}

      - name: Standardized Deplyment Process
        uses: docker://node:20-alpine
        shell: sh
        run: |
          echo "Deploying application to ${{ inputs.target-environment }}..."
          echo "Deployment completed successfully"
      
      - name: Register Deployment for Compliance
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ steps.register-artifact.outputs.artifact-id }}
          target-environment: ${{ inputs.target-environment}}